# Generated by Django 3.0.4 on 2020-04-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('post', models.CharField(max_length=999999)),
                ('image', models.ImageField(upload_to='')),
                ('file_link', models.CharField(max_length=200)),
                ('pub_name', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField()),
                ('slug', models.SlugField(max_length=500)),
            ],
        ),
    ]
