# Generated by Django 3.0.4 on 2020-04-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_model',
            name='image',
            field=models.ImageField(upload_to='Images/'),
        ),
        migrations.AlterField(
            model_name='blog_model',
            name='post',
            field=models.TextField(),
        ),
    ]
