# Generated by Django 3.0.4 on 2020-04-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0002_auto_20200421_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_model',
            name='post_prev',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
