# Generated by Django 3.0.4 on 2020-04-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0004_remove_blog_model_post_prev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_model',
            name='pub_date',
            field=models.DateTimeField(null=True),
        ),
    ]
